Reviewable settings directory docs and example file.
Reviewable/Reviewable pull request #1169
Opened 2024-07-15 02:57 UTC by unforswearing

Added my first pass at integrating the `.reviewable` settings docs into `repositories.md`. Also added an example `settings.yaml` file for review.

2024-07-22 02:06 UTC, pkaminski requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 16 unresolved discussions (waiting on @unforswearing)

___
*[`docs/repositories.md` line 99 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N5OZ_4-ofaqdR7dAg:-O2N5OZ_4-ofaqdR7dAh:bakp9ul) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L99)):*
> ```Markdown
> ## Repository settings
> `
> You may use using the GUI or by using the `.reviewable` directory in your project root. Please vist the [documentation for the `.reviewable` directory and `settings.yaml` file](#using-the-reviewable-directory) for more information.
> ```

"use using"?  "vist"?

visit -> see (throughout)
for more information -> for more information on the latter option.
___
*[`docs/repositories.md` line 132 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N678HAgRQxdA19As1:-O2N678HAgRQxdA19As2:b-64mah0) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L132)):*
> ```Markdown
> 
> {:.tip}
> If you are using the `.reviewable` settings directory, please visit the docs for using the [`badge` configuration option](#badge).
> ```

I think these tips are repetitive and don't add much value.  At the same time, it feels like the `.reviewable` option docs repeat a lot of information  already mentioned here.  What do you think about combining the two sections so that each option is documented just once and includes the information relevant to both the UI and file settings?
___
*[`docs/repositories.md` line 199 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NAr2B10IecUbI4mey:-O2NAr2C79_RX0Pmp5HR:bqwnbu7) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L199)):*
> ```Markdown
> ### Using the `.reviewable` Directory
> 
> The `.reviewable` settings directory will allow you to customize your review settings without manually changing settings using the Reviewable user interface. The `.reviewable` directory should contain a `settings.yaml` file and one or more optional custom completion scripts. 
> ```

It's actually valid to have just a completion script, or just a settings file with no completion scripts, or even neither (though that would be really weird and kinda useless).



_Suggestion:_
```Markdown
The `.reviewable` directory can contain a `settings.yaml` file and/or a completion script
(or more than one in case you're using repository-specific [overrides](link)).
```
___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N6NJm6BPx0Um-sOrm:-O2N6NJm6BPx0Um-sOrn:b-teqm9b) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
> ```Markdown
> 
> {:.important}
> An error is displayed if your `settings.yaml` file contains any options that are not valid, however Reviewable will continuue using the last settings that were synced with your repository. 
> ```

"continuue"
___
*[`docs/repositories.md` line 209 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N6Vqs1yw9-hzzDI6S:-O2N6Vqs1yw9-hzzDI6T:b-j7josi) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L209)):*
> ```Markdown
> ### The `settings.yaml` file
> 
> The `settings.yaml` file will allow you to update your reviewable settings for each repository. You may also create a master configuration file that will update settings for all repositories that are accessible via Reviewable. This master settings file will apply its settings to all repositories, regardless when they were created. You may add a local settings file in an individual repository to override settings from the master settings file.
> ```

reviewable -> Reviewable
all repositories -> all repositories in the organization
___
*[`docs/repositories.md` line 211 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N6fYgANCfUd9bJURc:-O2N6fYgANCfUd9bJURd:b-bvbpau) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L211)):*
> ```Markdown
> The `settings.yaml` file will allow you to update your reviewable settings for each repository. You may also create a master configuration file that will update settings for all repositories that are accessible via Reviewable. This master settings file will apply its settings to all repositories, regardless when they were created. You may add a local settings file in an individual repository to override settings from the master settings file.
> 
> The `settings.yaml` file provides several options used to configure the settings for one or more of your repositories. Settings listed in the top-level of this file are used as the default settings for the current repository. While a master settings file will determine the default settings for all repositories, this file can override its own default settings by using overrides. Additionally, any repository can override master settings by using a local settings file.
> ```

in the top-level -> at the top level
(please replace "top-level" with "top level" throughout)
___
*[`docs/repositories.md` line 211 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N78e68HWjoCshWM7e:-O2N78e68HWjoCshWM7f:undefined) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L211)):*
> ```Markdown
> The `settings.yaml` file will allow you to update your reviewable settings for each repository. You may also create a master configuration file that will update settings for all repositories that are accessible via Reviewable. This master settings file will apply its settings to all repositories, regardless when they were created. You may add a local settings file in an individual repository to override settings from the master settings file.
> 
> The `settings.yaml` file provides several options used to configure the settings for one or more of your repositories. Settings listed in the top-level of this file are used as the default settings for the current repository. While a master settings file will determine the default settings for all repositories, this file can override its own default settings by using overrides. Additionally, any repository can override master settings by using a local settings file.
> ```





_Suggestion:_
```Markdown
When a repository is designated as the master, its settings file will be used as the
basis for all repositories in the organization.  A master settings file can also provide
specialized settings for repositories via targeted in-file overrides.
```
___
*[`docs/repositories.md` line 213 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N6st28VS0b11P-B67:-O2N6st28VS0b11P-B68:bupzofb) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L213)):*
> ```Markdown
> The `settings.yaml` file provides several options used to configure the settings for one or more of your repositories. Settings listed in the top-level of this file are used as the default settings for the current repository. While a master settings file will determine the default settings for all repositories, this file can override its own default settings by using overrides. Additionally, any repository can override master settings by using a local settings file.
> 
> Below is an example of a few top-level settings in the `settings.yaml` file:
> ```

Should point to the example file as well.  Or perhaps just point to the example file here, then include a small option-specific example in each option's section.
___
*[`docs/repositories.md` line 229 at r1](https://reviewable.i [...]

2024-07-22 02:13 UTC, pkaminski requested changes
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 17 unresolved discussions (waiting on @unforswearing)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NBj5uDgUnKv5cOQsE:-O2NBj5uDgUnKv5cOQsF:b-kblcxe) (no related file):*
Also, I forgot to mention that we'll have the top two "later" features mentioned in the design doc ready for launch:  automated settings migration and a completion condition playground.  The latter is still WIP, but the former looks like this:
![image.png](https://files.reviewableusercontent.io/images/reviewable/1646896/xG8t-yhP6rY0lfJZ1CIb1eNn/image.png)
Note the small "Store settings in repo?" link.  When clicked, it opens an info panel with links to download the migrated settings, and the completion condition (if it's non-empty), and tells you where to put them:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/1646896/Bwre9TNC19hnos2-aMOheg5W/image.png)

___


<!-- Sent from Reviewable.io -->

2024-07-22 02:27 UTC, snoack reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 17 unresolved discussions (waiting on @pkaminski and @unforswearing)

___
*[`examples/settings/settings.yaml` line 22 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N3rQ-9L_bb_ivWzKT:-O2NFUom3KWlvk37rH-X:bmc4f5s) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L22)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think the indentation here is wrong:  both these values and `settings` below need to be indented one more level.  Can you confirm @snoack?
</blockquote></details>

Yes, there should be two more spaces before `settings` below. But I think the rest is indented correctly here.


<!-- Sent from Reviewable.io -->

2024-07-22 02:28 UTC, pkaminski requested changes
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 17 unresolved discussions (waiting on @unforswearing)



<!-- Sent from Reviewable.io -->

2024-07-23 00:14 UTC, snoack requested changes
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 22 unresolved discussions (waiting on @pkaminski and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O2Rol4A5apo5ATvJqtH:bxjr2qw) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
> ```Markdown
> 
> {:.important}
> An error is displayed if your `settings.yaml` file contains any options that are not valid, however Reviewable will continuue using the last settings that were synced with your repository. 
> ```

This is actually not true. If an invalid option is provided we fallback to the respective default for that option, not the last synced value.

The question is whether this is a bug in the implementation or in the documentation? Personally, I think the way it is implemented makes sense, unless I'm missing something. What so you think @pkaminski?
___
*[`docs/repositories.md` line 229 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N8-uR29ZGvoaVxFKw:-O2RpgwjADbPItmm9Lxo:blnbu2v) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L229)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This could probably be a `tip` instead.
</blockquote></details>

the reviewable -> Reviewable
___
*[`docs/repositories.md` line 264 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rr1WcClF1PWK7IHBS:-O2Rr1WcClF1PWK7IHBT:bmdyxio) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L264)):*
> ```Markdown
> default-review-style: one-per-commit
> overrides:
>   - repositories: dev*
> ```

How it's currently implemented `repositories` is always expected to be a list. So the example here would need to be converted to:

```yaml
- repositories:
  - dev*
```

Alternatively, I can change the implementation to support this kind of shorthand. However, I'm leaning towards sticking with the current implementation as it keeps the code and documentation simpler.

Note that the current revision of the documentation here besides using the shorthand in the example does not document it above.

@pkaminski, what do you think?
___
*[`docs/repositories.md` line 270 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2RsoRyELxWmQzemu_w:-O2RsoRyELxWmQzemu_x:b2d2woc) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L270)):*
> ```Markdown
> ```
> 
> ### Completion Condition Files
> ```

The word "file" hasn't been capitalized in other headings above.
___
*[`docs/repositories.md` line 272 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N9i-VC7tpbT7xHTtI:-O2RuQxyA_JlBVohPfDX:bw32mgj) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L272)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Should mention that Reviewable will use the file named `completion.js` by default if it exists and no override has named another file.
</blockquote></details>

Moreover, the only reason (I can think of) to explicitly set the `completion-file` settings is to configure different completion conditions for different repositories from within the master settings. So a more practical example would look like this:

```yaml
overrides:
  - repositories:
    - reviewable-*
    settings:
      completion-file: reviewable-completion.js
  - repositories:
    - hubkit
    settings:
      completion-file: hubkit-completion.js
```
___
*[`examples/settings/settings.yaml` line 10 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Ru6nR5kRUhd44nH3Y:-O2Ru6nR5kRUhd44nH3Z:undefined) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L10)):*
> ```YAML
> badge:
>   - location: description-bottom
>   - when: location
> ```





_Suggestion:_
```YAML
  location: description-bottom
  when: location
```
___
*[`examples/settings/settings.yaml` line 17 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2RuDiZ6nSV1fkNCjKf:-O2RuDiZ6nSV1fkNCjKg:undefined) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L17)):*
> ```YAML
> github-status-updates: always
> coverage:
>   - url: https://example.com/coverage
> ```





_Suggestion:_
```YAML
  url: https://example.com/coverage
```


<!-- Sent from Reviewable.io -->

2024-07-26 19:54 UTC, unforswearing commented
*[`docs/repositories.md` line 264 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rr1WcClF1PWK7IHBS:-O2kaplhCtHZRGRhP_aK:bo1ynjn) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L264)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

How it's currently implemented `repositories` is always expected to be a list. So the example here would need to be converted to:

```yaml
- repositories:
  - dev*
```

Alternatively, I can change the implementation to support this kind of shorthand. However, I'm leaning towards sticking with the current implementation as it keeps the code and documentation simpler.

Note that the current revision of the documentation here besides using the shorthand in the example does not document it above.

@pkaminski, what do you think?
</blockquote></details>

I have updated the yaml to match the existing implementation. 


<!-- Sent from Reviewable.io -->

2024-07-26 19:54 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 0 of 2 files reviewed, 17 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 132 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N678HAgRQxdA19As1:-O2kahIW08pTBjx8QyNx:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L132)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think these tips are repetitive and don't add much value.  At the same time, it feels like the `.reviewable` option docs repeat a lot of information  already mentioned here.  What do you think about combining the two sections so that each option is documented just once and includes the information relevant to both the UI and file settings?
</blockquote></details>

Done.
___
*[`docs/repositories.md` line 199 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NAr2B10IecUbI4mey:-O2kYQt01SgJkHgmNyIu:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L199)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

It's actually valid to have just a completion script, or just a settings file with no completion scripts, or even neither (though that would be really weird and kinda useless).
</blockquote></details>

Done.
___
*[`docs/repositories.md` line 211 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N78e68HWjoCshWM7e:-O2kafw84R1n3wP9cF27:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L211)):*
> ```Markdown
> The `settings.yaml` file will allow you to update your reviewable settings for each repository. You may also create a master configuration file that will update settings for all repositories that are accessible via Reviewable. This master settings file will apply its settings to all repositories, regardless when they were created. You may add a local settings file in an individual repository to override settings from the master settings file.
> 
> The `settings.yaml` file provides several options used to configure the settings for one or more of your repositories. Settings listed in the top-level of this file are used as the default settings for the current repository. While a master settings file will determine the default settings for all repositories, this file can override its own default settings by using overrides. Additionally, any repository can override master settings by using a local settings file.
> ```

Done.
___
*[`docs/repositories.md` line 213 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N6st28VS0b11P-B67:-O2kafdk2WBJn2oz1a1n:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L213)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Should point to the example file as well.  Or perhaps just point to the example file here, then include a small option-specific example in each option's section.
</blockquote></details>

Done.
___
*[`docs/repositories.md` line 253 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N9I_FCU_1kw2Vqg0A:-O2kanMJ9fJfktqF1PeG:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L253)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

When linking to a different docs file, include only the file name and anchor; the rest of the URL will be filled in automatically when the docs build.  So here, just `repositories.md#code-coverage` is sufficient.
</blockquote></details>

Done.
___
*[`docs/repositories.md` line 272 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N9i-VC7tpbT7xHTtI:-O2kb-V029hZgXSTPiEi:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L272)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Moreover, the only reason (I can think of) to explicitly set the `completion-file` settings is to configure different completion conditions for different repositories from within the master settings. So a more practical example would look like this:

```yaml
overrides:
  - repositories:
    - reviewable-*
    settings:
      completion-file: reviewable-completion.js
  - repositories:
    - hubkit
    settings:
      completion-file: hubkit-completion.js
```
</blockquote></details>

Done.
___
*[`examples/settings/settings.yaml` line 10 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Ru6nR5kRUhd44nH3Y:-O2cFFdH8mrH3fkLV_2H:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L10)):*
> ```YAML
> badge:
>   - location: description-bottom
>   - when: location
> ```

Done.
___
*[`examples/settings/settings.yaml` line 17 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2RuDiZ6nSV1fkNCjKf:-O2cF7ktCG3pUmk2YHUF:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L17)):*
> ```YAML
> github-status-updates: always
> coverage:
>   - url: https://example.com/coverage
> ```

Done.
___
*[`examples/settings/settings.yaml` line 22 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N3rQ-9L_bb_ivWzKT:-O2cF9kDEB8QS0pOvKV3:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L22)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Yes, there should be two more spaces before `settings` below. But I think the rest is indented correctly here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-26 22:07 UTC, unforswearing commented
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O2l47Wf89Fm7q7XfyLD:b-x05ftb) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

This is actually not true. If an invalid option is provided we fallback to the respective default for that option, not the last synced value.

The question is whether this is a bug in the implementation or in the documentation? Personally, I think the way it is implemented makes sense, unless I'm missing something. What so you think @pkaminski?
</blockquote></details>

Updated the docs to indicate Reviewable will fallback to the default value for the option, pending confirmation. 


<!-- Sent from Reviewable.io -->

2024-07-26 22:22 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 0 of 2 files reviewed, 16 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 99 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N5OZ_4-ofaqdR7dAg:-O2l5XDJCnbO15EEKLDH:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L99)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

"use using"?  "vist"?

visit -> see (throughout)
for more information -> for more information on the latter option.
</blockquote></details>

Done.
___
*[`docs/repositories.md` line 132 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N678HAgRQxdA19As1:-O2l5s001AOCc2-rtL_W:b4cwyg5) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L132)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

To clarify, "Done." rerferst to removing the `{.tip}` from each option. 

I like the idea of combining the docs -- the section for each option can contain sub-headings for GUI and `.reveiewable`. I can work on a version of this today and push the changes when the draft is updated. 


<!-- Sent from Reviewable.io -->

2024-07-27 17:47 UTC, unforswearing commented
*[`examples/settings/settings.yaml` line 8 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N2Jhy5eaaMxtbQNGN:-O2pIIA2AUgoztSsCaeK:bhrh3fa) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L8)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think each option should have a very short description and a list of valid values (if it's an enum) — basically, if you are generally familiar with Reviewable, you should be able to customize this file using only the information contained within.

We should also have pointers back to the docs for full details.  Perhaps per-option, though that many URLs might end up too messy, so one link to the docs section at the top could be better.
</blockquote></details>

Just pushed an update that includes a link to the docs under each option. Let me know if this is too noisy and I'll remove them. 


<!-- Sent from Reviewable.io -->

2024-07-27 18:08 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 0 of 2 files reviewed, 15 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`examples/settings/settings.yaml` line 26 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N3XNPB_Awr8pBOuB-:-O2pMyWPDfRpgAq36qjA:b-fi3it3) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L26)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

As a more effective example, let's only include some options in the override, give them different values than the parent, and summarize the merging mechanism.
</blockquote></details>

Added a summary, please verify for accuracy 


<!-- Sent from Reviewable.io -->

2024-07-27 18:22 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 0 of 2 files reviewed, 15 unresolved discussions (waiting on @pkaminski and @snoack)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NBj5uDgUnKv5cOQsE:-O2pQNDE9xeSTl8Yjgzi:b-18hlc0) (no related file):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Also, I forgot to mention that we'll have the top two "later" features mentioned in the design doc ready for launch:  automated settings migration and a completion condition playground.  The latter is still WIP, but the former looks like this:
![image.png](https://files.reviewableusercontent.io/images/reviewable/1646896/xG8t-yhP6rY0lfJZ1CIb1eNn/image.png)
Note the small "Store settings in repo?" link.  When clicked, it opens an info panel with links to download the migrated settings, and the completion condition (if it's non-empty), and tells you where to put them:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/1646896/Bwre9TNC19hnos2-aMOheg5W/image.png)
</blockquote></details>

Missed this earlier, my apologies. I'll incorporate these into the docs. 

___


<!-- Sent from Reviewable.io -->

2024-07-28 09:56 UTC, pkaminski reviewed
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 11 unresolved discussions (waiting on @snoack and @unforswearing)

___
*[`docs/repositories.md` line 132 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N678HAgRQxdA19As1:-O2shQCO5WNHU8J-zdzG:bgd2abn) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L132)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

To clarify, "Done." rerferst to removing the `{.tip}` from each option. 

I like the idea of combining the docs -- the section for each option can contain sub-headings for GUI and `.reveiewable`. I can work on a version of this today and push the changes when the draft is updated.
</blockquote></details>

OK, let's combine.  We might not even need subheadings if the `.reviewable` details are fairly short.
___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O2shqeT2ql-yjC5LMqn:b-3mm5am) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Updated the docs to indicate Reviewable will fallback to the default value for the option, pending confirmation.
</blockquote></details>

I think there are two cases:
1. If a given property value is invalid then it falls back to its default value.
2. If the entire settings file is malformed then IIRC we keep using the last version of the settings that synced successfully.  Is that right?
___
*[`docs/repositories.md` line 264 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rr1WcClF1PWK7IHBS:-O2sjMNkDKzhCAygeu4v:b-pbyxq5) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L264)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

I have updated the yaml to match the existing implementation.
</blockquote></details>

Oh, I thought we'd agreed to automatically convert a string value to a single-element array.  Would be a nice QoL upgrade and easy to add?
___
*[`docs/repositories.md` line 203 at r7](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2silQu5W_99v3T_lmj:-O2silQu5W_99v3T_lmk:b7qu5ju) ([raw file](https://github.com/Reviewable/Reviewable/blob/38c3ce7da878978dbca959721a85281d0e7a2adb/docs/repositories.md#L203)):*
> ```Markdown
> The `when` setting optionally allows you to specify when to inject the Reviewable badge into the pull request. This option will accept `accessed` or `published` as parameters.
> 
> {t.tip}
> ```

Typo: `{.tip}`
___
*[`docs/repositories.md` line 248 at r7](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2sjeeRE_0EETV94sEm:-O2sjeeRE_0EETV94sEn:bsp77t0) ([raw file](https://github.com/Reviewable/Reviewable/blob/38c3ce7da878978dbca959721a85281d0e7a2adb/docs/repositories.md#L248)):*
> ```Markdown
> ### Completion condition files
> 
> The `settings.yaml` file allows you to specify one or more completion condition files for an individual repository, or any repository listed in the `repositories` object of the master `settings.yaml` file. These completion files must be included in the same `.reviewable` directory as your `settings.yaml` file.  Reviewable will use a file named `completion.js` by default if it exists and no override is specified a different completion file to use.
> ```

"no override is specified a different" -> "no override specified a different"
___
*[`examples/settings/settings.yaml` line 8 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N2Jhy5eaaMxtbQNGN:-O2skEvA2GFtfwh45nKT:bcwx166) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L8)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Just pushed an update that includes a link to the docs under each option. Let me know if this is too noisy and I'll remove them.
</blockquote></details>

I think the links are OK, I'd just add an empty line between each top level option to space things out a bit.
___
*[`examples/settings/settings.yaml` line 26 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N3XNPB_Awr8pBOuB-:-O2skqE48E22ngJalIK-:b-1ys741) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L26)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Added a summary, please verify for accuracy
</blockquote></details>

Close.  I'd phrase it like this though:

These settings will override corresponding settings earlier in this file for the repositories listed above, and can in turn be overridden by a local settings file in a target repository.
___
*[`examples/settings/settings.yaml` line 50 at r7](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2skYnG5LoCPLopPf9I:-O2skYnG5LoCPLopPf9J:b-9b2h3z) ([raw file](https://github.com/Reviewable/Reviewable/blob/38c3ce7da878978dbca959721a85281d0e7a2adb/examples/settings/settings.yaml#L50)):*
> ```YAML
> overrides:
>   # `repositories` is a list of repositories that will apply the settings specified in the yaml file.
>   # The list of repositories may be a list of strings or `fnmatch`(glob) patterns.
> ```

Need space in front of `(glob)`.


<!-- Sent from Reviewable.io -->

2024-07-29 22:09 UTC, snoack reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 9 unresolved discussions (waiting on @pkaminski and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O2zxL3yAN8Yv3FyY_tg:b-gv8yer) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
> If a given property value is invalid then it falls back to its default value.

Correct.

> If the entire settings file is malformed then IIRC we keep using the last version of the settings that synced successfully. Is that right?

Until recently there was a bug and we would trigger an unhandled error if parsing the YAML file failed, and consequently any previously synced settings would persist as the function syncing the settings would never complete successfully. Since we handle this error, besides showing an appropriate warning, we treat an invalid YAML file the same as one that parses as `undefined` (e.g. an empty file), and that means all settings fall back to their respective default. I think these semantics make sense. What do you think?
___
*[`docs/repositories.md` line 264 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rr1WcClF1PWK7IHBS:-O3-SsqMAF0X-3BwkfRF:b-21nluc) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L264)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Oh, I thought we'd agreed to automatically convert a string value to a single-element array.  Would be a nice QoL upgrade and easy to add?
</blockquote></details>

Yeah, it was spec'd at some point but I forgot to implement it. If you think it's worth it, I go ahead and implement it.

I guess, then we should also document this in here?


<!-- Sent from Reviewable.io -->

2024-07-30 01:43 UTC, pkaminski reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 9 unresolved discussions (waiting on @snoack and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O30ID7LEGjU7YkAtrmN:bk50ggr) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
Here's what we specced in the design doc:
> **If file based settings don't parse/validate show error at repository settings, and at each review for that repository, but keep reviews functional based on last synced settings.**

IIRC we did this to minimize the chance of a repo-wide (or org-wide!) disruption and I think that rationale still makes sense.
___
*[`docs/repositories.md` line 264 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rr1WcClF1PWK7IHBS:-O30HecE8HNppBZrnGd3:b61dnz1) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L264)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Yeah, it was spec'd at some point but I forgot to implement it. If you think it's worth it, I go ahead and implement it.

I guess, then we should also document this in here?
</blockquote></details>

Yup, I'd just low-key document it by having a single-repo example as a direct string, and a multi-repo example elsewhere as a list.


<!-- Sent from Reviewable.io -->

2024-07-30 20:12 UTC, snoack reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 9 unresolved discussions (waiting on @pkaminski and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O33qodQ0XManJFqriw6:b-6cq38z) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Here's what we specced in the design doc:
> **If file based settings don't parse/validate show error at repository settings, and at each review for that repository, but keep reviews functional based on last synced settings.**

IIRC we did this to minimize the chance of a repo-wide (or org-wide!) disruption and I think that rationale still makes sense.
</blockquote></details>

Indeed we initially specified it like this. Though according to that specification we would not only persists any previously synced settings if the whole YAML file doesn't parse, but also if a setting's value is invalid. If we are OK with falling back to the default in the latter scenario, I think we should do the same when encountering a YAML syntax error. Otherwise, this inconsistency might be confusing. Also the YAML parser is very tolerant, and there aren't many ways in which you can cause it to fail. So this is kind of a rare scenario.


<!-- Sent from Reviewable.io -->

2024-07-31 02:42 UTC, pkaminski reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 9 unresolved discussions (waiting on @snoack and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O35dRz-45adO9OuXP1u:b-a4bz1) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Indeed we initially specified it like this. Though according to that specification we would not only persists any previously synced settings if the whole YAML file doesn't parse, but also if a setting's value is invalid. If we are OK with falling back to the default in the latter scenario, I think we should do the same when encountering a YAML syntax error. Otherwise, this inconsistency might be confusing. Also the YAML parser is very tolerant, and there aren't many ways in which you can cause it to fail. So this is kind of a rare scenario.
</blockquote></details>

I agree it should be consistent, and I still believe the rationale above is sound.  How about if we (conceptually) treat the current settings as the base layer in our merge stack (so current -> master -> overrides -> local)?  The only hitch with that approach is that the first missing or empty settings file needs to be considered as having all properties set to their default value, so it'll correctly wipe out the current settings.


<!-- Sent from Reviewable.io -->

2024-07-31 05:08 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 264 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rr1WcClF1PWK7IHBS:-O367OZ4-O-PMes54eaQ:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L264)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Yup, I'd just low-key document it by having a single-repo example as a direct string, and a multi-repo example elsewhere as a list.
</blockquote></details>

Done.
___
*[`examples/settings/settings.yaml` line 8 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N2Jhy5eaaMxtbQNGN:-O3680fi9JACEP3phPtR:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L8)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think the links are OK, I'd just add an empty line between each top level option to space things out a bit.
</blockquote></details>

Done.
___
*[`examples/settings/settings.yaml` line 26 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N3XNPB_Awr8pBOuB-:-O368Kqw3yW8Oc_PFeV7:bw75769) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L26)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Close.  I'd phrase it like this though:

These settings will override corresponding settings earlier in this file for the repositories listed above, and can in turn be overridden by a local settings file in a target repository.
</blockquote></details>

Thanks for the rephrasing. Pushing an update now. 


<!-- Sent from Reviewable.io -->

2024-07-31 05:26 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 132 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N678HAgRQxdA19As1:-O36EzykDExAWacR4rB9:bndupkv) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L132)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

OK, let's combine.  We might not even need subheadings if the `.reviewable` details are fairly short.
</blockquote></details>

Just pushed the combined docs. I kept the headings for the `settings.yaml` options, but let me know if you think its too noisy. 


<!-- Sent from Reviewable.io -->

2024-07-31 05:28 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`examples/settings/settings.yaml` line 26 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N3XNPB_Awr8pBOuB-:-O36FYDe8_VeTrmzZcXy:blab8vu) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L26)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Thanks for the rephrasing. Pushing an update now.
</blockquote></details>

Upon re-reading the edits, it does seem verbose. I'll work on an update, pending your feedback on this latest revision @pkaminski 


<!-- Sent from Reviewable.io -->

2024-07-31 12:17 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 132 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N678HAgRQxdA19As1:-O37iD8bAABdo8HwPN9v:bo0kdp1) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L132)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Just pushed the combined docs. I kept the headings for the `settings.yaml` options, but let me know if you think its too noisy.
</blockquote></details>

Reposting in the correct thread -- Upon re-reading the edits, it does seem verbose. I'll work on an update, pending your feedback on this latest revision [@pkaminski](https://github.com/pkaminski)
___
*[`examples/settings/settings.yaml` line 26 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2N3XNPB_Awr8pBOuB-:-O37i79g3gecLdF9jAKJ:biks7ja) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/examples/settings/settings.yaml#L26)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Upon re-reading the edits, it does seem verbose. I'll work on an update, pending your feedback on this latest revision @pkaminski
</blockquote></details>

Please disregard the above comment, added to the wrong thread. 


<!-- Sent from Reviewable.io -->

2024-07-31 14:06 UTC, pkaminski reviewed
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 15 unresolved discussions (waiting on @snoack and @unforswearing)

___
*[`docs/repositories.md` line 99 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O381wlB77P5vDwadPNN:-O381wlB77P5vDwadPNO:b-bqse2l) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L99)):*
> ```Markdown
> ## Repository settings
> 
> You may use the GUI or by using the `.reviewable` directory in your project root. Each description below will include setting options using the GUI ([reviewable.io/repositories](https://reviewable.io/repositories)) or by using the `settings.yaml` file in your `.reviewable` directory.
> ```

Looks like you inadvertently dropped "To configure settings for Reviewable".  Also "may use" / "by using" construction isn't grammatically correct.
___
*[`docs/repositories.md` line 127 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O383Qk28HqPl3Rc1WR1:-O383Qk28HqPl3Rc1WR2:b-93g041) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L127)):*
> ```Markdown
> ### Prototype settings for new repos
> 
> #### Using the GUI
> ```

This is the only subsection in the above section.  It's also redundant, as only a GUI-configured repo can be designated as the prototype for new repos.
___
*[`docs/repositories.md` line 132 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O382kl36yyVU-znMXII:-O382kl36yyVU-znMXIJ:b-lauyzr) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L132)):*
> ```Markdown
> 
> {:.tip}
> This feature is particularly useful if you chose to connect [all current and future repos](#connect-all-current-and-future-repos).
> ```

This is even more true for the master settings file.
___
*[`docs/repositories.md` line 146 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3830Uz1FcERWeK83Xr:-O3830Uz1FcERWeK83Xs:b-hf8syq) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L146)):*
> ```Markdown
> ### Applying a `settings.yaml` file to multiple repositories
> 
> Designate a master repository to store your `settings.yaml` file and any completion condition scripts. The settings in this master repository will be used for all repositories in your organization that are accessible via Reviewable (with the exception of [overrides](#overrides)). This master settings file will apply its settings to all repositories, regardless when they were created.
> ```

@snoack, are master settings also used for unconnected repos?
___
*[`docs/repositories.md` line 146 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3838fVAwYcvPzp__wx:-O3838fVAwYcvPzp__wy:b5eeeqk) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L146)):*
> ```Markdown
> ### Applying a `settings.yaml` file to multiple repositories
> 
> Designate a master repository to store your `settings.yaml` file and any completion condition scripts. The settings in this master repository will be used for all repositories in your organization that are accessible via Reviewable (with the exception of [overrides](#overrides)). This master settings file will apply its settings to all repositories, regardless when they were created.
> ```

"regardless _of_ when"
___
*[`docs/repositories.md` line 157 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O383tZM5JOLWUTA3UGP:-O383tZM5JOLWUTA3UGQ:b-hq81o) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L157)):*
> ```Markdown
> When you have one or more repositories with individual `settings.yaml` files, you may use a master repository that will determine default settings for all repositories that belong to an organization. These settings can be overriden in the `overrides` object of the master `settings.yaml` file.
> 
> The `overrides` property has two children. The `repositories` object is a list of repositories that will apply the settings specified in the yaml file. The list of repositories may be a list of strings or `fnmatch` (glob) patterns. For example, if you would like to apply default settings for any repository whose name begins with `dev`, you may use the following setting in your master `settings.yaml` file:
> ```

"specified in the yaml file" -> "specified in the `settings` property of this override"
___
*[`docs/repositories.md` line 157 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3847p-04a9L6GAGEKx:-O3847p-04a9L6GAGEKy:b-fm0okv) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L157)):*
> if you would like to apply default settings for any repository whose name begins with `dev`

The example doesn't match this description.
___
*[`docs/repositories.md` line 166 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O384EdV5GamhqBVsNPt:-O384EdV5GamhqBVsNPu:bs4q9op) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L166)):*
> ```Markdown
>     - fire*
>   settings:
>     # All repositories with names that start with `dev` will use "combined commits" for the `default-review-style` setting.
> ```

Ditto.
___
*[`docs/repositories.md` line 181 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3852RC2gKgvu9b-D8h:-O3852RD6dXezjPSQ9qc:b1dfo7f) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L181)):*
> ```Markdown
> Changes here are retroactive (except that an existing description badge won’t be moved to a comment), but will be applied lazily as reviews are visited.
> 
> #### The `badge` option in `settings.yaml`
> ```

Definitely too many subheadings this way.  How about presenting the file docs as a pretend type definition, something like:
```
badge:
  location: description-bottom | description-top | comment | none
  when: accessed | published
```

Extra information can be added as either comments or prose before/after the type definition, as appropriate.
___
*[`docs/repositories.md` line 185 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O384qTz1OnX2IFPTwDk:-O384qTz1OnX2IFPTwDl:b-t8ka6k) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L185)):*
> ```Markdown
> The `location` setting determines the location of the Reviewable badge in the pull request. The `location` parameter may include one of the following options: `description-bottom` (default), `description-top`, `comment`, or `none`.
> 
> The `when` setting optionally allows you to specify when to inject the Reviewable badge into the pull request. This option will accept `accessed` or `published` as parameters.
> ```

Please add the GUI docs for this option as well — thanks.
___
*[`docs/repositories.md` line 187 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O38-6Q_1Z9ueafXdTGG:-O38-6Q_1Z9ueafXdTGH:bshtxot) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L187)):*
> ```Markdown
> The `when` setting optionally allows you to specify when to inject the Reviewable badge into the pull request. This option will accept `accessed` or `published` as parameters.
> 
> {t.tip}
> ```

Typo.  Also, I don't think this tip is needed since the limitation on "None" are already described above.
___
*[`docs/repositories.md` line 200 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O384kp-7aR8oiFccn5U:-O384kp0Cgd8VFWSI0dH:bxlc0ak) ([ [...]

2024-07-31 16:53 UTC, snoack reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 14 unresolved discussions (waiting on @pkaminski and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O38hV306GNpvaWMVPmh:b-s0tlou) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I agree it should be consistent, and I still believe the rationale above is sound.  How about if we (conceptually) treat the current settings as the base layer in our merge stack (so current -> master -> overrides -> local)?  The only hitch with that approach is that the first missing or empty settings file needs to be considered as having all properties set to their default value, so it'll correctly wipe out the current settings.
</blockquote></details>

I will look into it.
___
*[`docs/repositories.md` line 146 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3830Uz1FcERWeK83Xr:-O38hGClArvnfbF0NPLd:b267bek) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L146)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

@snoack, are master settings also used for unconnected repos?
</blockquote></details>

Yes, they are.


<!-- Sent from Reviewable.io -->

2024-08-01 01:56 UTC, snoack reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 14 unresolved discussions (waiting on @pkaminski and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O3AdQry-KxIm08TWV-m:b1gtij9) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

One problem with that approach is that if we have to fetch the current settings in Firebase first then the IO operation is no longer atomic. We cannot use a transaction since we have to write (or reset) as well the completion condition at `:rules/:owner/:repo`, or at least we can't do so in the same transaction. While right now, with the current implementation everything is written in a single update operation which makes things more robust.  

Also with a merge order like *current settings* -> *settings files* removing a setting would have no effect which I doubt to be intended. That is because for any setting that isn’t defined in either settings file, we’d fall back to the current settings.

I think what you want instead is falling back to current settings only for invalid settings (that would be all settings if the whole file is invalid YAML). But then there are scenarios where we have a valid value for a setting in the master configuration, but an invalid value for the same setting in a local configuration. I guess in that case we would want to pick the valid value from the master settings instead of the current setting's value.

I started to work on a proof of concept, and I think it’s probably doable but it will make the logic significantly more complex. I personally think it is not worth it and I feel it makes the overall logic more error-prone, but if you insist I can continue going down this rabbit hole?
</blockquote></details>

For reference, untested draft PR: https://github.com/Reviewable/reviewable-server/pull/588

(As I said I would rather not add this complexity.) What do you think?


<!-- Sent from Reviewable.io -->

2024-08-01 09:58 UTC, pkaminski reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 13 unresolved discussions (waiting on @snoack and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O3CJuEE6_YQMsp_EF3z:bbrcttp) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

For reference, untested draft PR: https://github.com/Reviewable/reviewable-server/pull/588

(As I said I would rather not add this complexity.) What do you think?
</blockquote></details>

I haven't looked at the WIP but I think in principle the implementation could be fairly straightforward:
1. Load the current settings from Firebase.
2. If at any point a file fails to parse, capture the warning and return the current settings instead.
3. If at any point a property fails to validate, capture the warning and return the property from the current settings instead.

The only annoyance I can think of is that the file and Firebase contents have different schemas, so you'd need to be careful and skip further downstream parsing for case 2.

As for atomicity, we didn't have that to begin with since the GH fetches / Firebase update could race among concurrent syncs.  (For example, consider the following interleaved sequence:  sync A loads file from GH, user updates file, sync B loads file from GH, sync B writes to Firebase, sync A writes to Firebase.)  And especially for a fallback whose purpose is to prevent your repo / org from grinding to a halt, and that should shortly be superseded by a fixed file, I think that a bit of racing is a reasonable trade-off.

(As an aside, while design docs aren't written in stone it's definitely worth explicitly calling out any potential changes to them caused by implementation constraints so we can have these discussions earlier.)


<!-- Sent from Reviewable.io -->

2024-08-01 20:39 UTC, snoack reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 13 unresolved discussions (waiting on @pkaminski and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O3EYrpJ3ENgg4-K-78A:b-kpaidw) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I haven't looked at the WIP but I think in principle the implementation could be fairly straightforward:
1. Load the current settings from Firebase.
2. If at any point a file fails to parse, capture the warning and return the current settings instead.
3. If at any point a property fails to validate, capture the warning and return the property from the current settings instead.

The only annoyance I can think of is that the file and Firebase contents have different schemas, so you'd need to be careful and skip further downstream parsing for case 2.

As for atomicity, we didn't have that to begin with since the GH fetches / Firebase update could race among concurrent syncs.  (For example, consider the following interleaved sequence:  sync A loads file from GH, user updates file, sync B loads file from GH, sync B writes to Firebase, sync A writes to Firebase.)  And especially for a fallback whose purpose is to prevent your repo / org from grinding to a halt, and that should shortly be superseded by a fixed file, I think that a bit of racing is a reasonable trade-off.

(As an aside, while design docs aren't written in stone it's definitely worth explicitly calling out any potential changes to them caused by implementation constraints so we can have these discussions earlier.)
</blockquote></details>

Here we go: https://reviewable.io/reviews/Reviewable/reviewable-server/589

My previous approach was more complicated partially due to avoiding fetching the current settings first, and partially due to an attempt to more gracefully handle when we have a master and local settings file of which only one is invalid.

Your simpler approach is more manageable. But I'm not sure how I feel about an invalid master settings file blocking updates to the local settings file, and vice versa. Also that means we cannot update the completion condition, because if we cannot parse the settings file(s), we don't know where to load the completion condition from.

But I guess this is as good as it gets within reasonable effort. (I might still prefer though to just fall back to the default, as it keeps things more predictable, especially when files are merged. And ultimately we can't guard against every mistake a user might make here.)


<!-- Sent from Reviewable.io -->

2024-08-02 10:35 UTC, pkaminski reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 13 unresolved discussions (waiting on @snoack and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O3Hd-c-2lwXeduBFQCN:b3i80o8) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
> more gracefully handle when we have a master and local settings file of which only one is invalid

Ah, I was hoping the new method could handle this too.  I guess in my mind I saw the returned original value used throughout the rest of the pipeline as if though it had been loaded successfully from the file, just skipping any schema translation steps.  Would that be feasible?

> And ultimately we can't guard against every mistake a user might make here.

Agreed, it's just about limiting the blast radius for really bad mistakes.


<!-- Sent from Reviewable.io -->

2024-08-03 17:15 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 11 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 99 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O381wlB77P5vDwadPNN:-O3O7JWGCicWIPtaCgLM:bghdx4f) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L99)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Looks like you inadvertently dropped "To configure settings for Reviewable".  Also "may use" / "by using" construction isn't grammatically correct.
</blockquote></details>

Yup, I must not have applied the most recent changes to the combined doc. This will be fixed with the next push. 
___
*[`docs/repositories.md` line 127 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O383Qk28HqPl3Rc1WR1:-O3O7iAZ9xysp27VoiSg:b-g0qqpa) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L127)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This is the only subsection in the above section.  It's also redundant, as only a GUI-configured repo can be designated as the prototype for new repos.
</blockquote></details>

Thanks, this was a leftover from a previous revision that I did not remove. 
___
*[`docs/repositories.md` line 132 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O382kl36yyVU-znMXII:-O3O80O12TT2PPOF66pt:b-x9jez1) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L132)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This is even more true for the master settings file.
</blockquote></details>

Added a line about using a smaster ettings file for additional flexibility, linking to the "Applying a settings,yaml file to multiple repositories" section. 
___
*[`docs/repositories.md` line 157 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O383tZM5JOLWUTA3UGP:-O3OBilA0SCc_o5v0Pvo:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L157)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

"specified in the yaml file" -> "specified in the `settings` property of this override"
</blockquote></details>

Done.
___
*[`docs/repositories.md` line 157 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3847p-04a9L6GAGEKx:-O3OC1HxACqR2zikGAeS:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L157)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

> if you would like to apply default settings for any repository whose name begins with `dev`

The example doesn't match this description.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-03 18:07 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 185 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O384qTz1OnX2IFPTwDk:-O3OPBeBD6qyUOjAq8xC:b94g6ak) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L185)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Please add the GUI docs for this option as well — thanks.
</blockquote></details>

I am not able to click the checkbox for "but only if a review has been <menu>" -- seems like I don't have permission to access this option. Tested this on a few repositories. Not sure if related, but I am also unable to select the "None" option for "Reviewable Badge" in the GUI. 
___
*[`docs/repositories.md` line 200 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O384kp-7aR8oiFccn5U:-O3ONYBr0IcHoFTILdHD:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L200)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Looks like we're missing the GUI docs for this option.  Could you add them please?  Thanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-03 18:14 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 181 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3852RC2gKgvu9b-D8h:-O3ORX-Z4cxUz3LJxWeI:bi82qz4) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L181)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Definitely too many subheadings this way.  How about presenting the file docs as a pretend type definition, something like:
```
badge:
  location: description-bottom | description-top | comment | none
  when: accessed | published
```

Extra information can be added as either comments or prose before/after the type definition, as appropriate.
</blockquote></details>

I made a pass at adding these to the bottom of each section in the docs, let me know what you think. 


<!-- Sent from Reviewable.io -->

2024-08-04 04:17 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @pkaminski and @snoack)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NBj5uDgUnKv5cOQsE:-O3Q_e8k9CPJFjPDC5Ve:b-w2qezk) (no related file):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Missed this earlier, my apologies. I'll incorporate these into the docs.
</blockquote></details>

Added a tip referencing the "Store settings in repo?" link, let me know if this needs to be fleshed out a bit more. Will add the completion condition playground information when the feature is closer to being complete. 

___
___
*[`docs/repositories.md` line 185 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O384qTz1OnX2IFPTwDk:-O3Qa4oe-3rzlqbB7w_o:bmxtjmd) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L185)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

I am not able to click the checkbox for "but only if a review has been <menu>" -- seems like I don't have permission to access this option. Tested this on a few repositories. Not sure if related, but I am also unable to select the "None" option for "Reviewable Badge" in the GUI.
</blockquote></details>

I started this section with the information I have available, but the options I listed may not be accurate to the GUI settings. Let me know what options exist for this dropdown.


<!-- Sent from Reviewable.io -->

2024-08-04 14:23 UTC, pkaminski reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 5 unresolved discussions (waiting on @snoack and @unforswearing)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NBj5uDgUnKv5cOQsE:-O3SlQbk37jwXH2dfi_K:b-ogrk0t) (no related file):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

Added a tip referencing the "Store settings in repo?" link, let me know if this needs to be fleshed out a bit more. Will add the completion condition playground information when the feature is closer to being complete.
</blockquote></details>

A casual mention is sufficient here.  @snoack will let you know once the playground is ready to document, and provide the necessary details.

___
___
*[`docs/repositories.md` line 185 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O384qTz1OnX2IFPTwDk:-O3SjGnX7NxTIulGSq_p:bt1z114) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L185)):*
<details><summary><i>Previously, unforswearing (Alvin Charity) wrote…</i></summary><blockquote>

I started this section with the information I have available, but the options I listed may not be accurate to the GUI settings. Let me know what options exist for this dropdown.
</blockquote></details>

That option is only available if a subscription is active, but you can always check the contextual help for a description even if the component is disabled.  There are only two options in the dropdown:  visited (aka accessed) and started (aka published).
___
*[`docs/repositories.md` line 99 at r12](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3SijBq7WQOr0MeIdR6:-O3SijBrBQuzdm9jQuOG:by9ty01) ([raw file](https://github.com/Reviewable/Reviewable/blob/f3092c1ede91ed1fc1d9a086fa70c347d1db8ae0/docs/repositories.md#L99)):*
> ```Markdown
> ## Repository settings
> 
> To configure Reviewable repository settings you may use the [GUI](https://reviewable.io/repositories))or the `.reviewable` directory in your project root. Each description below will include setting options using the GUI or by using the `settings.yaml` file in your `.reviewable` directory.
> ```

Missing space in front of "or".
___
*[`docs/repositories.md` line 214 at r12](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3SkB0WDnm7CHC63G-Q:-O3SkB0X3NYBzU8E9Jx8:b-5b9rah) ([raw file](https://github.com/Reviewable/Reviewable/blob/f3092c1ede91ed1fc1d9a086fa70c347d1db8ae0/docs/repositories.md#L214)):*
> ```Markdown
> ### Default review overlap strategy
> 
> Determine the order in which reviews are conducted:
> ```

That's not quite right; please check the contextual help for a (slightly) better explanation.


<!-- Sent from Reviewable.io -->

2024-08-05 18:51 UTC, snoack reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 5 unresolved discussions (waiting on @pkaminski and @unforswearing)

___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O3Yr2ncDLr4q_MkRrj_:b56fn07) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

> more gracefully handle when we have a master and local settings file of which only one is invalid

Ah, I was hoping the new method could handle this too.  I guess in my mind I saw the returned original value used throughout the rest of the pipeline as if though it had been loaded successfully from the file, just skipping any schema translation steps.  Would that be feasible?

> And ultimately we can't guard against every mistake a user might make here.

Agreed, it's just about limiting the blast radius for really bad mistakes.
</blockquote></details>

As per the review linked above, the implementation has been changed to use the last synced value of a setting if the setting's new value is invalid, or in case the whole file cannot be parsed falling back to the last synced value for all settings. If settings cannot be parsed we also won't sync the completion condition (as we don't know where it's located). Local settings can still override invalid master settings.

The documentation needs to be updated accordingly.


<!-- Sent from Reviewable.io -->

2024-08-07 02:33 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 4 unresolved discussions (waiting on @pkaminski and @snoack)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NBj5uDgUnKv5cOQsE:-O3eaIz75eJoR_PGt9Uu:b-hfghm4) (no related file):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

A casual mention is sufficient here.  @snoack will let you know once the playground is ready to document, and provide the necessary details.
</blockquote></details>

Sounds good

___
___
*[`docs/repositories.md` line 205 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2Rol4A5apo5ATvJqtG:-O3ed6r48qmRVd1cCaul:bdxbaey) ([raw file](https://github.com/Reviewable/Reviewable/blob/1dc90b00d7dfcfd2155da30827beb5d5188c55a1/docs/repositories.md#L205)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

As per the review linked above, the implementation has been changed to use the last synced value of a setting if the setting's new value is invalid, or in case the whole file cannot be parsed falling back to the last synced value for all settings. If settings cannot be parsed we also won't sync the completion condition (as we don't know where it's located). Local settings can still override invalid master settings.

The documentation needs to be updated accordingly.
</blockquote></details>

Thanks @pkaminski and @snoack, I have updated the docs accordingly. 
___
*[`docs/repositories.md` line 185 at r9](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O384qTz1OnX2IFPTwDk:-O3ebWWo2P905T-LQXn4:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/c83c2d645e367c3e5b10dca5bcd54b9e06af04c5/docs/repositories.md#L185)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

That option is only available if a subscription is active, but you can always check the contextual help for a description even if the component is disabled.  There are only two options in the dropdown:  visited (aka accessed) and started (aka published).
</blockquote></details>

Done.
___
*[`docs/repositories.md` line 214 at r12](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3SkB0WDnm7CHC63G-Q:-O3ed21A8LD9xk1Ja616:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/f3092c1ede91ed1fc1d9a086fa70c347d1db8ae0/docs/repositories.md#L214)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

That's not quite right; please check the contextual help for a (slightly) better explanation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-11 02:32 UTC, pkaminski reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 2 unresolved discussions (waiting on @snoack and @unforswearing)

___
*[`docs/repositories.md` line 182 at r13](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3zGUcd4qTat5pCPj45:-O3zGUcd4qTat5pCPj46:b-szq5vl) ([raw file](https://github.com/Reviewable/Reviewable/blob/47d70d80bbc311860fb504414dfc5e6d2791e165/docs/repositories.md#L182)):*
> ```Markdown
> 
> * **Visited** - show the badge when the review has been accessed for the first time.
> * **Started** - only show the badge when the review has been published.
> ```

when the review -> once a review


<!-- Sent from Reviewable.io -->

2024-08-14 11:46 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`docs/repositories.md` line 182 at r13](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O3zGUcd4qTat5pCPj45:-O4FhKx69b8gwwjcVUqL:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/47d70d80bbc311860fb504414dfc5e6d2791e165/docs/repositories.md#L182)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

when the review -> once a review
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-14 19:24 UTC, pkaminski reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)



<!-- Sent from Reviewable.io -->

2024-08-23 19:59 UTC, pkaminski reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack and @unforswearing)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NBj5uDgUnKv5cOQsE:-O5-oWSQB8K_K4kTsVsy:bphenpb) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

The Completion Condition Playground is now online under https://reviewable.io/playground. It's essentially the same component used in the settings UI, but you cannot save the completion condition code but only test/debug it in the playground. Also since the component is used outside of a repo context in the playground you are required to enter a repository. Let me know if you have any further question regarding the Completion Condition Playground.
</blockquote></details>

One extra note:  you can also paste in a PR or review URL into the PR box instead of entering the data manually.

___


<!-- Sent from Reviewable.io -->

2024-08-25 04:05 UTC, unforswearing reviewed
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-O2NBj5uDgUnKv5cOQsE:-O56hNeL40sqUEZL-uOV:bxe52j3) (no related file):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

One extra note:  you can also paste in a PR or review URL into the PR box instead of entering the data manually.
</blockquote></details>

A tip regarding the completion condtion playground has been added. Please let me know if any edits are required.

___


<!-- Sent from Reviewable.io -->

2024-08-25 04:27 UTC, pkaminski reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1169#-:-O56mOtY0KR-58ylAdb0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @unforswearing)



<!-- Sent from Reviewable.io -->

2024-08-25 18:17 UTC, merged